# 
# REQUIREMENTS
# Default AWS credentials have access to manage new hosted zone
#
# EXECUTE
# ansible-playbook ./playbooks/setup_team.yml --extra-vars "team=<<<teamname>>>"
#
---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - event-vars.yml

  tasks:
    - sts_assume_role:
        aws_access_key: "{{ lookup('ini', 'aws_access_key_id section=neccdc-admin {{ ini_file }}') }}"
        aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section=neccdc-admin {{ ini_file }}') }}"
        role_arn: "arn:aws:iam::{{ account }}:role/OrganizationAccountAccessRole"
        role_session_name: "{{ team_name }}"
        region: "us-east-1"
      register: assumed_role
                   
    - name: Create team admin group
      iam_group:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        state: present
        name: TeamAdminGroup
        managed_policy:
          - arn:aws:iam::aws:policy/AdministratorAccess
        
    - name: Create team key-pair
      ec2_key:
        region: "us-east-1"
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        state: present
        force: true
        name: "{{ team_name }}"
      register: ec2_key
      
    - debug: var=ec2_key

    - name: Save private key
      copy: content="{{ ec2_key.key.private_key }}" dest="../../campus_data/{{ team_name }}.pem" mode=400
      when: ec2_key.changed

    - name: Create new access key
      iam:
        iam_type: user
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        state: present
        name: TeamAdmin
        access_key_state: create
        key_count: 1
        groups: TeamAdminGroup
      register: user
      
    - debug: var=user.user_meta.access_keys

    - name: Update access_key
      ini_file:
        path: "~/.aws/credentials"
        section: "{{ team_nme }}"
        option: aws_access_key_id
        value: "{{ user.user_meta.access_keys[0].access_key_id }}"

    - name: Update secret_key
      ini_file:
        path: "~/.aws/credentials"
        section: "{{ team_name }}"
        option: aws_secret_access_key
        value: "{{ user.user_meta.access_keys[0].secret_access_key }}"

